### ISSUE TITLE
setState can be called after the widget is disposed

### ISSUE THREAD

**Issue by hacker1024** [joshmatta/paging_library#5]
This happens if the widget is disposed while data is being fetched.

**Comment by hacker1024** [comment]
I've fixed this in #6 .

**Comment by lekeCoder** [comment]
Hello, I am still having this issue. I used this library in 4 tabs and this error keeps popping up whenever I click the third or fourth tab. What can l do?
